osx: build electrum-vtc

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -117,9 +117,9 @@ info "generating locale"
     fi
     cd "$CONTRIB"/deterministic-build/electrum-locale
     # we want the binary to have only compiled (.mo) locale files; not source (.po) files
-    rm -rf "$PROJECT_ROOT/electrum/locale/"
+    rm -rf "$PROJECT_ROOT/electrum_vtc/locale/"
     for i in ./locale/*; do
-        dir="$PROJECT_ROOT/electrum/$i/LC_MESSAGES"
+        dir="$PROJECT_ROOT/electrum_vtc/$i/LC_MESSAGES"
         mkdir -p "$dir"
         msgfmt --output-file="$dir/electrum.mo" "$i/electrum.po" || true
     done
@@ -129,29 +129,29 @@ info "generating locale"
 info "Installing some build-time deps for compilation..."
 brew install autoconf automake libtool gettext coreutils pkgconfig
 
-if [ ! -f "$PROJECT_ROOT"/electrum/libsecp256k1.0.dylib ]; then
+if [ ! -f "$PROJECT_ROOT"/electrum_vtc/libsecp256k1.0.dylib ]; then
     info "Building libsecp256k1 dylib..."
     "$CONTRIB"/make_libsecp256k1.sh || fail "Could not build libsecp"
 else
     info "Skipping libsecp256k1 build: reusing already built dylib."
 fi
-cp "$PROJECT_ROOT"/electrum/libsecp256k1.0.dylib "$CONTRIB"/osx
+cp "$PROJECT_ROOT"/electrum_vtc/libsecp256k1.0.dylib "$CONTRIB"/osx
 
-if [ ! -f "$PROJECT_ROOT"/electrum/libzbar.0.dylib ]; then
+if [ ! -f "$PROJECT_ROOT"/electrum_vtc/libzbar.0.dylib ]; then
     info "Building ZBar dylib..."
     "$CONTRIB"/make_zbar.sh || fail "Could not build ZBar dylib"
 else
     info "Skipping ZBar build: reusing already built dylib."
 fi
-cp "$PROJECT_ROOT"/electrum/libzbar.0.dylib "$CONTRIB"/osx
+cp "$PROJECT_ROOT"/electrum_vtc/libzbar.0.dylib "$CONTRIB"/osx
 
-if [ ! -f "$PROJECT_ROOT"/electrum/libusb-1.0.dylib ]; then
+if [ ! -f "$PROJECT_ROOT"/electrum_vtc/libusb-1.0.dylib ]; then
     info "Building libusb dylib..."
     "$CONTRIB"/make_libusb.sh || fail "Could not build libusb dylib"
 else
     info "Skipping libusb build: reusing already built dylib."
 fi
-cp "$PROJECT_ROOT"/electrum/libusb-1.0.dylib "$CONTRIB"/osx
+cp "$PROJECT_ROOT"/electrum_vtc/libusb-1.0.dylib "$CONTRIB"/osx
 
 
 info "Installing requirements..."
@@ -195,9 +195,9 @@ if [ ! -z "$CODESIGN_CERT" ]; then
 fi
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
+hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-vtc-$VERSION.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/electrum-${VERSION}.dmg"
+DoCodeSignMaybe ".DMG" "dist/electrum-vtc-${VERSION}.dmg"
 
 if [ -z "$CODESIGN_CERT" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
